spring:
  application:
    name: server-api-gateway
  profiles:
    active: ${PROFILES:default}
  config:
    import: configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}